spring:
  profiles: dev
  application:
    name: user
  zipkin:
    baseUrl: http://10.10.35.236:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 0.1
  datasource:
    druid:
      name: druid-dev
      url: jdbc:mysql://127.0.0.1:3306/tcc2?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&charset=utf8mb4&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      max-active: 10
      initial-size: 3
      max-wait: 30000
      min-idle: 2
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 150000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      remove-Abandoned: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
    type: com.alibaba.druid.pool.DruidDataSource

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 15000
  eureka:
    enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 30000
  routes:
    users:
      path: /user/**
      sensitiveHeaders: "*"
      serviceId: user
      stripPrefix: false

add-proxy-headers: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

secret:
  map: "{127: 'asdfg', 256: 'qwert'}"